const texts: { [key: string]: string } = {
  teacherPortal: 'פורטל מורים"',
  studentPortal: "פורטל תלמידים",
  createNewLesson: "צור שיעור חדש",
  myLessons: "השיעורים שלי",
  headline: "כּוֹתֶרֶת",
  description: "תיאור",
  instructions: "הוראות",
  language: "שפה",
  hebrew: "עיברית",
  arabic: "עֲרָבִית",
  addQr: "הוסף QR",
  chooseType: "בחר סוג",
  uploadPhoto: "הקלד/העלאה",
  delete: "לִמְחוֹק",
  image: "תמונה",
  send: "שלח",

  signupWelcome: "נעים להכיר!",
  firstName: "שם פרטי",
  lastName: "שם משפחה",
  email: "דואר אלקטרוני",
  passWord: "סיסמה",
  confirmPassword: "אימות סיסמה",
  alreadyHaveAnAccount: "כבר יש לך חשבון?",

  loginWelcome: "Login",
};
